all: readme help
	@echo

### Help
readme:  ### Show README.md with colors in terminal
	@echo
	@awk 'BEGIN {FS="";} \
	/^#/ {printf "\033[1;34m%s\033[0m\n", $$0; next}    # Überschriften (blau) \
	/^>/ {printf "\033[1;36m%s\033[0m\n", $$0; next}    # Zitate (cyan) \
	/^-/ {printf "\033[1;33m%s\033[0m\n", $$0; next}    # Listenpunkte (gelb) \
	/^\*/ {printf "\033[1;32m%s\033[0m\n", $$0; next}   # Fettgedrucktes (grün) \
	{print $$0}' README.md

help:	### This lines shows available commands marked with 3# in this Makefile
	@awk 'BEGIN {FS = ":.*## "; printf "\n\033[1;34m==== Available Commands ====\033[0m\n"} \
	/^### / {printf "\n\033[1;33m%s\033[0m\n", substr($$0, 5)} \
	/^[a-zA-Z0-9_-]+:.*## / {printf "  \033[36m%-20s\033[0m %s\n", $$1, $$2} \
	' $(MAKEFILE_LIST)



